baseURL: "https://www.johnsilvan.xyz/"
title: John Silvan
paginate: 5
theme: PaperMod 

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "John Silvan's Personal Website"
    author: John Silvan

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: Home 
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
                  - Title: "Home"
                    Content: "Welcome to my corner of the internet. My [Blog](/archives) is a loose collection of thoughts, things learned, and who-knows-whats.This site should be available soon as **JSON** and **RSS**."
                  - Title: "Work"
                    Content: "I'm a Software Developer at HSBC Technology in Pune, India.
            Here's my resume in [HTML](/resume/resume.html) and [JSON](/resume/resume.json)"
                  - Title: "Education"
                    Content: "I have a B.tech in Computer Science from [VIT](https://vit.ac.in/) and a Post Graduate Diploma in Machine Learning & Artificial Intelligence from [IIITB](https://www.iiitb.ac.in/)"
                  - Title: "Contact"
                    Content: "Wanna get in touch? Email me at mailme@johnsilvan.xyz or johnsilvan70@gmail.com.<br>Find me elsewhere on [Github](https://github.com/johnsilvan) and [Linkedin](https://www.linkedin.com/in/johnsilvan/)"
                  - Title: "Various"
                    Content: "“**Get in over your head as often and as joyfully as possible.**” – Alexander Isley, Designer and American Institute of Graphic Arts medalist"
 

            


    socialIcons:
        - name: github
          url: "https://github.com/johnsilvan"
        - name: RsS
          url: "index.html"

    editPost:
        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "/favicon.ico"
    #     favicon16x16: "/favicon-16x16.png"
    #     favicon32x32: "/favicon-32x32.png"
    #     apple_touch_icon: "/apple-touch-icon.png"
    #     safari_pinned_tab: "<link / abs url>"
 
    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
