---
- hosts: all
  become: true
  vars:
    create_containers: 1 
    default_container_name: johnsilvan.xyz 
    default_container_image: johnsilvan/johnsilvan.xyz:0.1 

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        published_ports: 80:80
        state: started 
      with_sequence: count={{ create_containers }}

