---
- hosts: all
  become: true
  vars_files:
   - vars/default.yml
  vars:
    default_container_image: johnsilvan/johnsilvan.xyz:{{ version }} 

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        published_ports: 80:80
        state: started 
      with_sequence: count={{ create_containers }}

